# Generated by Django 3.2.7 on 2021-09-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_auto_20210909_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='domesticado',
            new_name='domestico',
        ),
    ]
